<html lang="pl">
<head>
    <title><?=__('page_title')?></title>
    <meta charset="utf-8">
    <script src="/data/js/jquery-3.2.1.js"></script>
    <script src="/data/js/app.js?ver=<?=APP_VER?>"></script>
    <link rel="stylesheet" type="text/css" href="/data/css/flags16.css">
    <link rel="stylesheet" type="text/css" href="/data/css/site.css?ver=<?=APP_VER?>">
</head>
<script>
    App.init();
</script>
<body>
<div id="container">